### ISSUE TITLE
Feature Request : Warn / prevent connector from adding duplicate entries to the database

### ISSUE THREAD

**Issue by jcalbert** [zotero/zotero-connectors#221] opened 2018-02-23 19:39 UTC
I often "re-discover" papers and end up adding duplicates to my library.  It would be nice if Zotero connector, when adding an item to the database, would say something like

"The item [THIS] appears to be a duplicate of [THAT].  What would you like to do: [merge entries], [skip], [add anyway]"

**Comment by dstillman** [comment] 2018-03-06 10:55
Duplicate of https://github.com/zotero/zotero/issues/1007

Please post feature requests and bug reports to the Zotero Forums.

**Closed by dstillman** 2018-03-06 10:55 UTC

**Comment by jcalbert** [comment] 2018-03-07 06:20
Oops, sorry.

**Comment by HsunGong** [comment] 2022-05-20 15:11
Comment here again, as I think this can also be a zotero-connector feature to prevent the issue https://github.com/zotero/zotero/issues/1007.

Or we may develop a new plugin to solve it. As I've mentioned here at https://github.com/zotero/zotero/issues/1007#issuecomment-1133011175
