### ISSUE TITLE
Save shortcut in Safari

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#180] opened 2017-09-14 03:18 UTC
Not ideal, but we <a href="http://antrikshy.com/blog/safari-extension-development-keyboard-shortcuts">could do it</a> by listening for the shortcut in an injected script.

Requested: https://forums.zotero.org/discussion/67618/keyboard-shortcut-key-combo-hotkey-for-saving-reference-in-safari-extension

**Comment by adomasven** [comment] 2018-04-06 12:01
Duplicate of https://github.com/zotero/zotero-connectors/issues/60

**Closed by adomasven** 2018-04-06 12:01 UTC
