### ISSUE TITLE
More reliable error feedback when clicking save button

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#202] opened 2017-11-14 12:48 UTC
It seems there are still various situations where the button does nothing. We should figure out what those are and try to fix them.

E.g., https://forums.zotero.org/discussion/68674/chrome-connector-does-not-work

(In some situations people might just be missing the partially empty saving popup, though that report also shows 0 translators in cache, so maybe more was going on.)

It would also be nice to either disable the button or do something (anything) when clicking the button on a privileged page.

**Comment by adomasven** [comment] 2018-04-06 12:07
This was primarily caused by failed script injections. We have sinced changed the injection mechanism and the reports have stopped. Closing for now.

**Closed by adomasven** 2018-04-06 12:07 UTC
